# Generated by Django 2.2.10 on 2020-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='time_received',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materials',
            name='date_received',
            field=models.DateField(),
        ),
    ]
